### ISSUE TITLE
docker compose 部署报错

### ISSUE THREAD

**Issue by ShadowWaIker** [WeOps-Lab/OpsPilot#34]
按照 [快速入门文档](https://wedoc.canway.net/opspilot/quick-start.html) 中的步骤操作，docker compose 部署报错，如下：
![image](https://github.com/WeOps-Lab/OpsPilot/assets/10329893/70d5340d-eeba-4a85-8910-21d9f2446ce8)

直接在浏览器中打开镜像连接，提示 UNAUTHORIZED
![image](https://github.com/WeOps-Lab/OpsPilot/assets/10329893/e8d4cc1f-d4fe-4738-b0c4-f3c74384ab7c)

应当是 image 配置为了私有仓库，请提供有访问权限的仓库账号或将仓库配置为公开仓库

**Comment by etherfurnace** [comment]
1. 2.0的OpsPilot默认切换为K8S的运行模式了
2. 镜像编译出来比较大，腾讯云有限速，传到后面很慢，暂时还是需要自行编译镜像哟
