### ISSUE TITLE
Pilot 服务5005端口访问提示没有监听

### ISSUE THREAD

**Issue by ChrisZhang789** [WeOps-Lab/OpsPilot#57]
在访问 Pilot 的5005端口的时候，报错没有监听，在访问Pilot的5055的时候，提示没有对应的URL路由，查看/var/log/supervisor 没有报错日志，请问要如何排查，谢谢。

![QQ20240704-170400](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/ec39ad0c-a371-4596-8d94-ff9d34945e90)

**Comment by etherfurnace** [comment]
Pilot要在Munchkin上上线，才会被拉起来，在这里
![image](https://github.com/WeOps-Lab/OpsPilot/assets/81210463/ccefcde7-f7a1-486f-9a0b-84e99d1d0d9a)

**Comment by ChrisZhang789** [comment]
> Pilot要在Munchkin上线，才会被拉起来，在这里 ![图像](https://private-user-images.githubusercontent.com/81210463/346025706-ccefcde7-f7a1-486f-9a0b-84e99d1d0d9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjY4MDAsIm5iZiI6MTcyMDE2NjUwMCwicGF0aCI6Ii84MTIxMDQ2My8zNDYwMjU3MDYtY2NlZmNkZTctZjdhMS00ODZmLTlhMGItODRlOTlkMWQwZDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA4MDE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NTJlMjlkNmZlZTdiODcyZDQ3OTI3OTZhNDY4ZjRkZTU2M2ZhNmQyNjg5ZDk1OTU0NTNmNDhlNWRiZTc3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uitUp7NwNmmBsktjSREcEBdtzZNevMb3yUs8xfSSPE8)

![QQ20240705-160232](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/d9f020f7-8f1c-4244-8c9d-d17b2cb5e0bc)
是的，是通过 Munchkin 拉起来的，nodeport 的端口范围是默认的，所以写了35005，目前通过nodeport 或者在容器内部，都无法访问到Pilot的 5005，supervisor日志没报错，pod运行状态也是正常的。

**Comment by etherfurnace** [comment]
可以看看Munchkin的后台日志，上线失败会有日志提示的，进入Munchkin的容器，supervisorctl tail -f munchkin 可以查看到日志

**Comment by ChrisZhang789** [comment]
![20240706193829](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/0bf232dd-a7a9-426f-b4e7-982f889fb48f)
Munchkin 重新拉起 Pilot Pod,没看到报错，但是 Pilot  的5005 访问依然失败。

**Comment by etherfurnace** [comment]
我看了一下截图，你的端口映射开在了35005，对外端口现在是35005啦

**Comment by ChrisZhang789** [comment]
35005 无法访问，原因是因为 Pilot 的 pod 没有监听5005，您可以用官方文档的镜像启动一个试试看。
参考: 
`https://wedoc.canway.net/opspilot/quick-start.html`
`docker pull ccr.ccs.tencentyun.com/megalab/pilot
`

**Comment by etherfurnace** [comment]
不是这样启动的，pilot是Munchkin调度启动，默认会有一个clusterIP，开在5005。你在界面上配了端口映射，会开一个nodeport出来，可以看k8s的svc有没成功启动
![image](https://github.com/WeOps-Lab/OpsPilot/assets/81210463/d6d2b7d9-ae39-4f8c-a899-cc1387d74e03)

正常的长这样
![image](https://github.com/WeOps-Lab/OpsPilot/assets/81210463/4a35ba95-7547-46df-9979-6dc515301107)
![image](https://github.com/WeOps-Lab/OpsPilot/assets/81210463/caaeda54-b6a9-4dbf-9e87-66346d917669)

PS:
     docker pull ccr.ccs.tencentyun.com/megalab/pilot  这样不会启动端口，因为内部是supervisor启动的

**Comment by ChrisZhang789** [comment]
![QQ20240708281354](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/6f4ec07d-253b-450e-84a0-fd83f3b39296)

![QQ2024070831425](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/12cfb7a8-4481-4fd5-9a7f-ab2d45a90aaf)

没问题的，我在pod 里面运行 ` rasa shell --endpoints  endpoints.yml  --credentials  credentials.yml ` ,提示 `No model found. Train a model before running the server using rasa train`., pod 里面 cache/model/下面是有model 文件的。

我这个没有监听有可能是因为rasa启动的问题。

![QQ20240708682032](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/fbd84f65-6ba6-4e34-9ce0-1a8a5a443f34)

**Comment by etherfurnace** [comment]
可以进pilot的supervisor里面看看ops-pilot的日志信息，看看是不是rasa进程启动失败了🤔

**Comment by ChrisZhang789** [comment]
解决了， 虚拟机的cpu指令集缺少 avx，导致transformers报非法指令错误，rasa启动失败，添加指令集后，问题解决，感谢。

**Comment by etherfurnace** [comment]
👍
