### ISSUE TITLE
在对话框输入内容，没有对话

### ISSUE THREAD

**Issue by TurboChow** [WeOps-Lab/OpsPilot#6]
在对话框输入内容，没有对话，日志打印：Ignoring message as there is no agent to handle it

**Comment by etherfurnace** [comment]
请描述清楚启动方式、提供截图和完整的日志信息

**Comment by TurboChow** [comment]
<img width="851" alt="image" src="https://github.com/WeOps-Lab/OpsPilot/assets/5257857/3fc72954-951a-4046-b3b6-45e41d366159">
<img width="843" alt="image" src="https://github.com/WeOps-Lab/OpsPilot/assets/5257857/0fdd89c3-c76f-4b10-9d86-886415d0b937">

**Comment by etherfurnace** [comment]
直接用Docker-Compose启动，是缺少Model和Bert这些基础模型的，需要重新训练模型，才可以使用哦，训练方式可以参考文档~~
