### ISSUE TITLE
部署时对GPU的规格要求

### ISSUE THREAD

**Issue by wushifeng** [WeOps-Lab/OpsPilot#61]
这个工程使用了多个模型，推理时的性能有测试的数据吗？
GPU的规格和这些服务支持的并发量是什么情况

**Comment by etherfurnace** [comment]
使用了K8S的架构，整体是无状态服务，直接横向扩容就好啦，不同模型情况不一样哦，例如同样是Embed，FastEmbed比BCE EMbed性能会快几十倍（CPU下~~）
