### ISSUE TITLE
关于通道配置问题

### ISSUE THREAD

**Issue by ChrisZhang789** [WeOps-Lab/OpsPilot#64]
请问关于通道的配置和使用，有没有详细的文档，目前使用的是 web，前端通过 socket去访问。

pilot报错提示：
通道:[socketio],会话ID:[VNgeRfya62rf2BY_AAAB]. 请求服务异常:Expecting value: line 1 column 1 (char 0),用户输入的信息为:who are you

![QQ20240710aa81320](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/39e05171-a5e5-46ab-bd1b-63f28d9c3503)
![QQ20240710aa81358](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/3c66d035-4b81-4034-9d93-2d0deb4aa21f)

请问关于项目的前后端，有没有比较详细的部署或使用文档，谢谢。

**Comment by ChrisZhang789** [comment]
##### 配置了通义千问的模型，也配置了技能。
##### 模型
![QQ202407bbbb00438](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/f7c76d35-a236-4d74-bbbd-45296f978e0b)
=====
##### 技能
![QQ202407bbbb00507](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/150c952f-e6b6-43b1-a14a-8abc75a89083)
====
##### 机器人配置
![QQ202407bbbb00550](https://github.com/WeOps-Lab/OpsPilot/assets/17696820/e06e3326-84c6-4d7c-b8a3-0dfdf8eff064)

**Comment by etherfurnace** [comment]
可以看看munchkin的日志提示，话说chat server现在只支持openai和chatglm耶，其他还没做适配，可能是api兼容问题。当然也可以用oneapi统一转成openai模式

**Comment by ChrisZhang789** [comment]
用oneapi中转国产的模型，问答正常了。

请问关于基于SaltStack集成的自动化，是要添加LLM技能吧，要自己写Agent + Prompt吗，有示例demo吗，感谢。

**Comment by ChrisZhang789** [comment]
用OneApi中转国产模型，问答正常了，十分感谢。

期待 RoadMap 后面推出的新内容。
